# Run: Ctrl + Alt + R
GET http://localhost:5002/contacts HTTP/1.1
###
GET http://localhost:5002/contacts/1 HTTP/1.1

###
POST http://localhost:5002/contacts HTTP/1.1
content-type: application/json

{
    "name": "Sara",
    "email": "sara@test.com",
    "contact": "contact sara"
}
###
PUT http://localhost:5002/contacts/2 HTTP/1.1
content-type: application/json

{
    "name": "Sara2",
    "email": "sara2@test.com",
    "contact": "contact sara2"
}
###
DELETE  http://localhost:5002/contacts/2 HTTP/1.1


